# ***Q1: Questions on Basic NumPy ***

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
#arr[::-1]
print(np.flip(arr))

[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [5]:

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.flatten())
print(array1.ravel())

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]]) arr2 = np.array([[1, 2], [3, 4]])

In [7]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 1]])
print(np.array_equal(arr1,arr2))

False


(d) Find the most frequent value and their indice(s) in the following arrays:

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [12]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
val1=np.bincount(x).argmax()
print(val1)
indices=np.where(x==val1)
print(indices)

val2=np.bincount(y).argmax()
print(val2)
indices1=np.where(y==val2)
print(indices1)

1
(array([0, 5, 7, 8, 9]),)
1
(array([0, 1, 2]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find Sum of all elements

i)Sum of all elements

ii)Sum of all elements row-wise


iii)Sum of all elements column-wise

In [19]:
get_config=np.get_printoptions()
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

#i
print(np.sum(gfg))
print("\n")
#ii
print(np.sum(gfg,axis=1))
print("\n")
#iii
print(np.sum(gfg,axis=0))


45


[[14]
 [16]
 [15]]


[[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i) Sum of diagonal elements

ii) Eigen values of matrix

iii)Eigen vectors of matrix

iv) Inverse of matrix

v) Determinant of matrix

In [25]:
n_array=np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
#i
print(n_array.diagonal().sum())
print('\n')

#ii
print(np.linalg.eigvals(n_array))
print('\n')

#iii
print(np.linalg.eig(n_array))
print('\n')

#iv
print(np.linalg.inv(n_array))
print('\n')

#v
print(np.linalg.det(n_array))

176


[98.16835147 28.097044   49.73460452]


EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))


[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


137180.0000000001



(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i)

p = [[1, 2], [2, 3]]   

q = [[4, 5], [6, 7]]

ii)

p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]

In [29]:
#i
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print(np.dot(p,q))
print('\n')
print(np.cov(p.flatten(),q.flatten()))

[[16 19]
 [26 31]]


[[0.66666667 1.        ]
 [1.         1.66666667]]


In [30]:
#ii
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
print(np.dot(p,q))
print('\n')
print(np.cov(p.flatten(),q.flatten()))


[[16 19  5]
 [26 31  8]
 [46 55 14]]


[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product

In [31]:
x=np.array([[2, 3, 4], [3, 2, 9]])
y=np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x,y))
print('\n')
print(np.outer(x,y))
print('\n')
print(np.cross(x,y))

[[17 52]
 [13 62]]


[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


[[-20   4   7]
 [-84  36  20]]



# **Q2: Based on NumPy Mathematics and Statistics**




(a)
For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i) Find element-wise absolute value

ii)Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.


iii)Mean, Median and Standard Deviation of flattened array, of each column, and each row

In [32]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
#i
print(np.absolute(array))
print('\n')



[[1 2 3]
 [4 5 6]]




In [35]:


# ii)Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.
print("25th percentile of flattened array: ", np.percentile(array, 25))
print("50th percentile of flattened array: ", np.percentile(array, 50))
print("75th percentile of flattened array: ", np.percentile(array, 75))
print('\n')
print("25th percentile of 1st column: ", np.percentile(array, 25, axis=0))
print("50th percentile of 2nd column: ", np.percentile(array, 50, axis=0))
print("75th percentile of 3rd  column: ", np.percentile(array, 75, axis=0))
print('\n')
print("25th percentile of 1st row: ", np.percentile(array, 25, axis=1))
print("50th percentile of 2nd row: ", np.percentile(array, 50, axis=1))
print("75th percentile of 3rd row: ", np.percentile(array, 75, axis=1))


25th percentile of flattened array:  -3.5
50th percentile of flattened array:  -0.5
75th percentile of flattened array:  2.5


25th percentile of 1st column:  [-2.75 -0.25 -3.75]
50th percentile of 2nd column:  [-1.5  1.5 -1.5]
75th percentile of 3rd  column:  [-0.25  3.25  0.75]


25th percentile of 1st row:  [-0.5 -5. ]
50th percentile of 2nd row:  [ 1. -4.]
75th percentile of 3rd row:  [2.  0.5]


In [37]:
#Mean, Median and Standard Deviation of flattened array, of each column, and each row

print("Mean of flattened array: ", np.mean(array))
print("Median of flattened array: ", np.median(array))
print("Standard Deviation of flattened array: ", np.std(array))
print('\n')
print("Mean of 1st column: ", np.mean(array,axis=0))
print("Median of 2nd column: ", np.median(array,axis=0))
print("Standard Deviation of 3rd  column: ", np.std(array, axis=0))
print('\n')
print("Mean of 1st row: ", np.mean(array, axis=1))
print("Median of 2nd row: ", np.median(array,axis=1))
print("Standard Deviation of 3rd row: ", np.std(array,axis=1))



Mean of flattened array:  -0.5
Median of flattened array:  -0.5
Standard Deviation of flattened array:  3.8622100754188224


Mean of 1st column:  [-1.5  1.5 -1.5]
Median of 2nd column:  [-1.5  1.5 -1.5]
Standard Deviation of 3rd  column:  [2.5 3.5 4.5]


Mean of 1st row:  [ 0.66666667 -1.66666667]
Median of 2nd row:  [ 1. -4.]
Standard Deviation of 3rd row:  [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [38]:
a=np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print('\n')
print(np.ceil(a))
print('\n')
print(np.trunc(a))
print('\n')
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]


[-1. -1. -0.  1.  2.  2.  3.]


[-1. -1. -0.  0.  1.  1.  3.]


[-2. -2. -0.  0.  2.  2.  3.]


# **Q3: Based on Searching and Sorting**

a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

 iii. 4 smallest elements

 iv. 5 largest elements


In [39]:
#i
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))

[ 10  16  16  52  54  62 453]


In [45]:
#ii
print('The indices of sorted arry with respect to its original arry is:')
print(np.argsort(array))

The indices of sorted arry with respect to its original arry is:
[0 3 4 1 5 2 6]


In [42]:
#iii
print('Four smallest number are:')
print(np.sort(array)[:4])

Four smallest number are:
[10 16 16 52]


In [47]:
#iv
print('Five largest number in ascending order  are:')
print(np.sort(array)[-5:])

Five largest number in ascending order  are:
[ 16  52  54  62 453]
